app.port=${APP_PORT:8082}

db.url=${DB_URL:jdbc:postgresql://localhost:5435/library_db}
db.username=${DB_USERNAME:vyachic007}
db.password=${DB_PASSWORD:postgres}

jwt.secret=${JWT_SECRET:library-management-system-super-secret-key-minimum-32-characters}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}